on: [push]

jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: farhanmohammadshaikh/msp430-gcc-9.3.1.11:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build the project
        run: TOOLS_PATH=/home/ubuntu/dev/tools/msp430-gcc make HW=NSUMO
        run: TOOLS_PATH=/home/ubuntu/dev/tools/msp430-gcc make HW=LAUNCHPAD

      - name: Run static analysis with cppcheck
        run: make cppcheck

